const byId = <T extends HTMLElement>(id: string): T => {
  const element = document.getElementById(id);
  if (!element) throw new Error(`Missing element #${id}`);
  return element as T;
};

export const dom = {
  html: document.documentElement,
  brandLink: byId<HTMLAnchorElement>("brand-link"),
  asciiLogo: byId<HTMLElement>("ascii-logo"),
  langSwitcher: byId<HTMLSelectElement>("lang-switcher"),
  themeSwitcher: byId<HTMLSelectElement>("theme-switcher"),
  langLabel: byId<HTMLSpanElement>("lang-label"),
  themeLabel: byId<HTMLSpanElement>("theme-label"),
  treeHome: byId<HTMLAnchorElement>("tree-home"),
  treeArticles: byId<HTMLAnchorElement>("tree-articles"),
  treeTags: byId<HTMLAnchorElement>("tree-tags"),
  quickNav: document.querySelector<HTMLElement>(".quick-nav") ?? byId<HTMLElement>("tree-home").parentElement as HTMLElement,
  pwdLine: byId<HTMLElement>("pwd-line"),
  listView: byId<HTMLElement>("article-list-view"),
  homeFilesPanel: byId<HTMLElement>("home-files-panel"),
  articleView: byId<HTMLElement>("article-view"),
  errorView: byId<HTMLElement>("error-view"),
  welcomePanel: byId<HTMLElement>("welcome-panel"),
  welcomeCommand: byId<HTMLElement>("welcome-command"),
  articlesPanel: byId<HTMLElement>("articles-panel"),
  tagsPanel: byId<HTMLElement>("tags-panel"),
  welcomeTitle: byId<HTMLElement>("welcome-title"),
  welcomeLead: byId<HTMLElement>("welcome-lead"),
  welcomeBody: byId<HTMLElement>("welcome-body"),
  tocPanel: byId<HTMLElement>("toc-panel"),
  tocList: byId<HTMLUListElement>("toc-list"),
  listTitle: byId<HTMLElement>("list-title"),
  articleSearchInput: byId<HTMLInputElement>("article-search-input"),
  tagSearchInput: byId<HTMLInputElement>("tag-search-input"),
  sortLabel: byId<HTMLElement>("sort-label"),
  sortSelect: byId<HTMLSelectElement>("sort-select"),
  sizeLabel: byId<HTMLElement>("size-label"),
  pageSizeSelect: byId<HTMLSelectElement>("page-size-select"),
  tagSortLabel: byId<HTMLElement>("tag-sort-label"),
  tagSortSelect: byId<HTMLSelectElement>("tag-sort-select"),
  tagSizeLabel: byId<HTMLElement>("tag-size-label"),
  tagPageSizeSelect: byId<HTMLSelectElement>("tag-page-size-select"),
  tagsHeadline: byId<HTMLElement>("tags-headline"),
  tagList: byId<HTMLUListElement>("tag-list"),
  articleList: byId<HTMLUListElement>("article-list"),
  pagePrev: byId<HTMLButtonElement>("page-prev"),
  pageInfo: byId<HTMLElement>("page-info"),
  pageNext: byId<HTMLButtonElement>("page-next"),
  tagPagePrev: byId<HTMLButtonElement>("tag-page-prev"),
  tagPageInfo: byId<HTMLElement>("tag-page-info"),
  tagPageNext: byId<HTMLButtonElement>("tag-page-next"),
  articleContent: byId<HTMLElement>("article-content"),
  renderIndicator: byId<HTMLElement>("render-indicator"),
  downloadPdfBtn: byId<HTMLButtonElement>("download-pdf-btn"),
  editArticleBtn: byId<HTMLButtonElement>("edit-article-btn"),
  zenModeBtn: byId<HTMLButtonElement>("zen-mode-btn"),
  zenExitBtn: byId<HTMLButtonElement>("zen-exit-btn"),
  processLog: byId<HTMLElement>("process-log"),
  footerMotto: byId<HTMLElement>("footer-motto"),
  backLink: byId<HTMLAnchorElement>("back-link"),
  errorTitle: byId<HTMLElement>("error-title"),
  errorText: byId<HTMLElement>("error-text")
};
